tap 'homebrew/bundle'
tap 'homebrew/cask-fonts'

brew 'hub'
brew 'gnupg'
brew 'gettext'
brew 'git-secret'
brew 'coreutils'
brew 'getantibody/tap/antibody'
brew 'autojump'
brew 'go'
brew 'hub'
brew 'jq'
brew 'grc'
brew 'openssl'
brew 'yarn'
brew 'imagemagick'

tap 'drone/drone'
brew 'drone'

cask 'keka'
cask 'docker'
cask '1password'
cask 'firefox'
cask 'google-chrome'
cask 'rambox'
cask 'bettertouchtool'
cask 'aerial'
cask 'spotify'
cask 'hyper'
cask 'google-cloud-sdk'
cask 'visual-studio-code'

cask 'font-lato'
cask 'font-open-sans'
cask 'font-hasklig'