tap 'homebrew/bundle'
tap 'homebrew/cask-fonts'

brew 'antibody'
brew 'go'
brew 'jq'
brew 'grc'
brew 'openssl'
brew 'yarn'
brew 'imagemagick'

cask '1password'
cask 'firefox'
cask 'google-chrome'
cask 'rambox'
cask 'bettertouchtool'
cask 'aerial'
cask 'spotify'
cask 'hyper'

cask 'font-lato'
cask 'font-open-sans'
cask 'font-hasklig'