cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'antibody'
brew 'go'
brew 'jq'
brew 'grc'
brew 'openssl'
brew 'yarn'
brew 'imagemagick'

cask '1password'
cask 'firefox'
cask 'google-chrome'
cask 'rambox'
cask 'bettertouchtool'
cask 'aerial'
cask 'spotify'
case 'hyper'