#!/bin/zsh

# typeset -U config_files
# config_files=($ZSH/**/*.zsh)

# for file in ${(M)config_files:#*/pre-commit.zsh}
# do
#   source $file
# done

# unset config_files

$ZSH/bin/log_info "Running git secret hide."
git secret hide -m
