alias tf="terraform"
alias tfi="terraform init"
alias tfp="terraform plan"
alias tfa="terraform apply"
alias tft="terraform taint"
alias tfs="terraform state"
alias tfsl="terraform state list"
alias tfss="terraform state show $*"
