theme = "ayu_mirage"

[editor]
cursorline = true
auto-save = true

[editor.whitespace.render]
space = "all"
tab = "all"

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.file-picker]
hidden = false
