#!/usr/bin/env bash
# Start here

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

set -e

echo 'Welcome aboard, I will turn your mac in a dev machine now\n'
echo 'First things first...\n'

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

setup_gitconfig () {
  if ! [ -f git/gitconfig.local.symlink ]
  then
    info 'setup gitconfig'

    git_credential='cache'
    if [ "$(uname -s)" == "Darwin" ]
    then
      git_credential='osxkeychain'
    fi

    user ' - What is your github author name?'
    read -e git_authorname
    user ' - What is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.local.symlink.example > git/gitconfig.local.symlink

    success 'gitconfig'
  fi
}

install_dotfiles () {
	info 'installing dotfiles'
	for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
	do
		dst="$HOME/.$(basename "${src%.*}")"
		$DOTFILES_ROOT/bin/link-file "$src" "$dst"
	done
}

install_brew () {
	# If we're on a Mac, let's install and setup homebrew.
	if [ "$(uname -s)" == "Darwin" ]
	then
		info "installing dependencies"
		if source bin/dot | while read -r data; do info "$data"; done
		then
			success "dependencies installed"
		else
			fail "error installing dependencies"
		fi
	fi
}

setup_gitconfig
install_dotfiles
install_brew

echo '\n BOOM! All installed!'
