#!/usr/bin/env bash

set -o errexit  # abort on nonzero exitstatus
set -o nounset  # abort on unbound variable
set -o pipefail # don't hide errors within pipes
set -o xtrace   # print execution commands

ok () {
  echo "✅ $1"
}

################
# SYSTEM SETUP #
################

function install_system_updates () {
	# echo "🤖 Install latest OS updates"
	# sudo softwareupdate -i -a

	# Install command tools
	if [[ `xcode-select -p 1>/dev/null;echo $?` != 0 ]];then
		echo "🤖 Installing latest xcode tools, the machine will be restarted after the installation is complete."
		sudo xcode-select --install
		sudo shutdown -r now
	fi

	if [ "$(arch)" == "arm64" ];then
		echo "🤖 Enable Rosetta 2"
		softwareupdate --install-rosetta
	fi

	echo "🤖 Enable installation from unverified developers status: $(spctl --status)"
}

function install_homebrew() {
	if test ! $(which brew)
	then
		echo "🤖 Installing Homebrew"
		/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
			# Inject brewfile path loading into zprofile which is used by ZSH
		(echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> "$HOME/.zprofile"
		eval "$(/opt/homebrew/bin/brew shellenv)"
	fi
}


function install_gitconfig () {
echo "🤖 Configuring gitconfig"
  if ! [ -f git/gitconfig.local ]
  then
    echo "Creating gitconfig.local file"

    echo "- What is your github author name ❓"
    read -e git_author_name
    echo "- What is your github author email ❓"
    read -e git_author_email

    sed -e "s/AUTHOR_NAME/$git_author_name/g" -e "s/AUTHOR_EMAIL/$git_author_email/g" git/gitconfig.local.example > git/gitconfig.local

	echo "🤖 Linking gitconfig files"
	$DOTS/bin/link-file "${DOTS}/git/gitconfig" "${HOME}/.gitconfig"
	$DOTS/bin/link-file "${DOTS}/git/gitconfig.local" "${HOME}/.gitconfig.local"
	$DOTS/bin/link-file "${DOTS}/git/gitignore" "${HOME}/.gitignore"

    ok "gitconfig configured"
  fi
}

function install_dotfiles () {
	echo "🤖 Installing dotfiles"

	# make sure this folder exists
	mkdir -p "${HOME}/.config"

	echo "🤖 Configuring shells"
	# fish
	mkdir -p "${HOME}/.config/fish"
	$DOTS/bin/link-file "${DOTS}/fish" "${HOME}/.config/fish"
	ok "fish configured"

	# theme config for ZSH
	$DOTS/bin/link-file "${DOTS}/config/p10k.zsh" "${HOME}/.p10k.zsh"

	# zsh
	$DOTS/bin/link-file "${DOTS}/zsh/zshrc" "${HOME}/.zshrc"
	$DOTS/bin/link-file "${DOTS}/zsh/zsh_plugins.txt" "${HOME}/.zsh_plugins.txt"
	ok "zsh configured"

	echo "🤖 Configuring terminals & text editors"
	# alacritty config
	mkdir -p "${HOME}/.config/alacritty"
	$DOTS/bin/link-file "${DOTS}/config/alacritty.yml" "${HOME}/.config/alacritty/alacritty.yml"
	ok "Alacritty terminal configured"

	# ghostty config
	mkdir -p "${HOME}/.config/ghostty"
	$DOTS/bin/link-file "${DOTS}/config/ghostty" "${HOME}/.config/ghostty/config"
	ok "Ghostty terminal configured"

	# tmux config
	$DOTS/bin/link-file "${DOTS}/config/tmux.conf" "${HOME}/.tmux.conf"
	ok "tmux configured"

	# helix config
	mkdir -p "${HOME}/.config/helix"
	$DOTS/bin/link-file "${DOTS}/config/helix.toml" "${HOME}/.config/helix/config.toml"
	ok "Helix editor configured"

	echo "🤖 Configuring tools"
	# k9s config
	$DOTS/bin/link-file "${DOTS}/config/k9s_hotkey.yml" "${HOME}/.k9s/hotkey.yml"
	ok "k9s configured"

	# ripgrep config
	$DOTS/bin/link-file "${DOTS}/config/ripgreprc" "${HOME}/.ripgreprc"
	ok "ripgrep configured"

	# editor key bindings
	# Symlinks for app preferences are disabled since Sonoma.
	# That's why this copies files after any changes in settings.
	# This way the changes can be saved and committed.
	echo "🤖 Configuring XCode, Zed and VSCode keybindings"
	cp -f "${DOTS}/config/xcode.idekeybindings" "${HOME}/Library/Developer/Xcode/UserData/KeyBindings/Default.idekeybindings"
	cp -f "${DOTS}/config/zed-keymap.json" "${HOME}/.config/zed/keymap.json"
	cp -f "${DOTS}/config/vscode-keybindings.json" "${HOME}/Library/Application Support/Code/User/keybindings.json"


	echo "🤖 Configuring Karabiner key remapping"
	# keyboard remapping
	mkdir -p "${HOME}/.config/karabiner"
	touch "${HOME}/.config/karabiner/karabiner.json"
	$DOTS/bin/link-file "${DOTS}/config/karabiner.edn" "${HOME}/.config/karabiner.edn"
	echo "🤖 Install Karabiner Settings"
	goku
	ok "Karabiner configured"

	# MacOS Ding Sounds when Valid shortcuts are pressed
	# https://github.com/microsoft/vscode/issues/44070
	# https://code.visualstudio.com/docs/terminal/basics#_why-does-macos-make-a-ding-sound-when-i-resize-terminal-split-panes
	# This is because of Electron...
	# This is a workaround - this will turn of the ding sound
	mkdir -p ~/Library/KeyBindings
	cat > ~/Library/KeyBindings/DefaultKeyBinding.dict <<EOF
{
"@^\UF700" = "noop:";
"@^\UF701" = "noop:";
"@^\UF702" = "noop:";
"@^\UF703" = "noop:";
"@~^\UF700" = "noop:";
"@~^\UF701" = "noop:";
"@~^\UF702" = "noop:";
"@~^\UF703" = "noop:";
}
EOF
	ok "MacOS Ding sounds on valid shortcuts silence configured"

	# convenient links
	$DOTS/bin/link-file "${HOME}/Dropbox/src" "${HOME}/src"
	ok "Convenient links configured"
}

function install_brew_packages () {
	if [ "$(uname -s)" == "Darwin" ]
	then
		echo "🤖 Installing brew packages"
		if source bin/dot | while read -r data; do echo -e "$data"; done
		then
			echo "✅ Brew packages installed"
		else
			echo "❌ Error installing brew packages"
		fi
	fi
}

function install_fish () {
	echo "🤖 Add fish to the list of allowed shells"
	if ! grep -Fxq "$(which fish)" /etc/shells; then
		echo "$(which fish)" | sudo tee -a /etc/shells
	fi

	echo "🤖 Set fish as default shell"
	chsh -s "$(which fish)"

	# this needs to be installed from within the fish itself already
	echo "🤖 Installing fisher plugin manager for fish"
	curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
	ok

	echo "🤖 Install Tide theme for fish"
	fisher install IlanCosman/tide@v6
	ok

	echo "🤖 Install fzf for fish"
	fisher install patrickf3139/fzf.fish
	ok

	ok "fish configured"
}

function install_fonts () {
	echo "🤖 Installing fonts"
	git clone https://github.com/powerline/fonts.git --depth=1
	cd fonts
	./install.sh
	cd ..
	rm -rf fonts
	ok "powerline fonts installed"
}

function install_language_versions () {
	echo "🤖 Installing language versions"
	mise use --global go@latest
	mise use --global python@latest
	mise use --global ruby@latest
	mise use --global terraform@latest
	mise use --global temurin@21
	mise use --global node@24
	ok "Language versions installed"
}

# Do we need to ask for sudo password or is it already passwordless?
# grep -q 'NOPASSWD:     ALL' /etc/sudoers.d/$LOGNAME > /dev/null 2>&1
# if [ $? -ne 0 ]; then
#   echo "no suder file"
#   sudo -v

#   # Keep-alive: update existing sudo time stamp until the script has finished
#   while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# fi

function install_macos_defaults () {
	$DOTS/bin/set-macos-defaults
}

################
# EXECUTE      #
################
echo "🤖 Welcome aboard, I will turn your mac into a dev machine now"
cd "$(dirname "$0")/.."
DOTS=$(pwd -P)

install_system_updates
install_homebrew
install_brew_packages
install_language_versions
install_dotfiles

# install_fish
install_fonts
install_macos_defaults
install_gitconfig

ok 'Done! May the Force be with you!'
