# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# zmodload zsh/zprof # uncomment to profile laoding speed
export ZSH=${HOME}/.dotfiles

# 1. Load paths and ENVs
source "${ZSH}/zsh/env.zsh"

# 2. Load aliases
source "${MY_ALIASES}/aliases.sh"
source "${MY_FUNCTIONS}/functions.sh"

# 3. Load version managers
source "${ZSH}/zsh/versions.zsh"

# 4. Fuzzy finder (needs to be loaded BEFORE compinit)
# alt+c - trigger OR "cd **<TAB>"
[ -f "${HOME}/.fzf.zsh" ] && source "${HOME}/.fzf.zsh"

# 5. ZSH config (autoload compinit)
source "${ZSH}/zsh/config.zsh"

# 6. fzf-tab - fuzzy search with a simple tab (needs to be loaded AFTER compinit)
source "${ZSH}/zsh/plugins/fzf-tab/fzf-tab.plugin.zsh"

# 7. Plugins
# Add new plugins to the `zsh_plugins.txt` file and reload zsh
# Keep syntax highlighting plugin last!
source ${BREW_PREFIX}/opt/antidote/share/antidote/antidote.zsh
antidote load

# 8. Load misc tools

# Amazing git add, log, diff, reset, checkout, stash, clean
[ -f "$BREW_PREFIX/share/forgit/forgit.plugin.zsh" ] && source "$BREW_PREFIX/share/forgit/forgit.plugin.zsh"
# Numbered git output

[[ -x "${BREW_PREFIX}/bin/scmpuff" ]] && eval "$(scmpuff init -s)"

# Better cd navigation (like autojump)
[[ -x "${BREW_PREFIX}/bin/zoxide" ]] && eval "$(zoxide init zsh --cmd j)"

# Colored output for common unix commands
[[ -s "${BREW_PREFIX}/etc/grc.bashrc" ]] && source "${BREW_PREFIX}/etc/grc.bashrc"

# Load theme
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
source ${BREW_PREFIX}/share/powerlevel10k/powerlevel10k.zsh-theme
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/opt/homebrew/share/google-cloud-sdk/path.zsh.inc' ]; then . '/opt/homebrew/share/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/opt/homebrew/share/google-cloud-sdk/completion.zsh.inc' ]; then . '/opt/homebrew/share/google-cloud-sdk/completion.zsh.inc'; fi

##################
# FOOTER        #
##################

# Local variables, aliases, functions
[[ -s "${ZSH}/zsh/.zshrc.local" ]] && source "${ZSH}/zsh/.zshrc.local"

complete -o nospace -C /Users/gbko/.config/tfenv/versions/1.14.0/terraform terraform

autoload -U +X bashcompinit && bashcompinit

### Nothing should be after this line - if you see anything present
# most likely some script/tool added it there. Find the right place for it

# zprof # uncomment to profile loading speed
